#!/usr/bin/env python3
"""
Test script for newly deployed AgentCore Gateway
Works with any gateway configuration file generated by deploy_retail_gateway.py
"""

import json
import sys
import subprocess
import os

def test_gateway_with_curl(config_file):
    """Test gateway using curl commands"""
    
    # Load configuration
    try:
        with open(config_file, 'r', encoding='utf-8') as f:
            config = json.load(f)
    except FileNotFoundError:
        print(f"❌ Configuration file not found: {config_file}")
        return False
    
    print(f"🧪 Testing Gateway: {config['gateway_id']}")
    print(f"URL: {config['gateway_url']}")
    print("=" * 60)
    
    # Get OAuth token
    print("🔑 Getting OAuth token...")
    
    try:
        import requests
        token_response = requests.post(
            config['token_endpoint'],
            headers={'Content-Type': 'application/x-www-form-urlencoded'},
            data={
                'grant_type': 'client_credentials',
                'client_id': config['client_id'],
                'client_secret': config['client_secret'],
                'scope': config['scope']
            },
            timeout=30
        )
        token_response.raise_for_status()
        access_token = token_response.json().get('access_token')
        
        if not access_token:
            print(f"❌ No access token in response: {token_response.text}")
            return False
        
        print("✅ Token acquired successfully")
        
    except Exception as e:
        print(f"❌ Token acquisition failed: {e}")
        return False
    
    # Test tools list
    print("\n📋 Listing available tools...")
    
    tools_cmd = [
    
    try:
        tools_response = requests.post(
            config['gateway_url'],
            headers={
                'Authorization': f'Bearer {access_token}',
                'Content-Type': 'application/json'
            },
            json={"jsonrpc": "2.0", "id": 1, "method": "tools/list"},
            timeout=30
        )
        tools_response.raise_for_status()
        tools = tools_response.json().get('result', {}).get('tools', [])
        
        print(f"✅ Found {len(tools)} tools:")
        for tool in tools[:5]:  # Show first 5 tools
            print(f"   - {tool['name']}: {tool.get('description', 'No description')}")
        
        if len(tools) > 5:
            print(f"   ... and {len(tools) - 5} more tools")
        
    except Exception as e:
        print(f"❌ Tools list failed: {e}")
        return False
    
    # Test health check (find the health check tool)
    health_tool = None
    for tool in tools:
        if 'health' in tool['name'].lower():
            health_tool = tool['name']
            break
    
    if health_tool:
        print(f"\n🔍 Testing {health_tool}...")
        
        
        try:
            health_response = requests.post(
                config['gateway_url'],
                headers={
                    'Authorization': f'Bearer {access_token}',
                    'Content-Type': 'application/json'
                },
                json={
                    "jsonrpc": "2.0",
                    "id": 1,
                    "method": "tools/call",
                    "params": {
                        "name": health_tool,
                        "arguments": {}
                    }
                },
                timeout=30
            )
            health_response.raise_for_status()
            health_data = health_response.json()
            if 'error' in health_data:
                print(f"❌ Health check error: {health_data['error']}")
            else:
                print("✅ Health check successful")
                    
        except Exception as e:
            print(f"❌ Health check failed: {e}")
    
    # Test products list (find the products tool)
    products_tool = None
    for tool in tools:
        if 'product' in tool['name'].lower() and 'list' in tool['name'].lower():
            products_tool = tool['name']
            break
    
    if products_tool:
        print(f"\n📦 Testing {products_tool}...")
        
        try:
            products_response = requests.post(
                config['gateway_url'],
                headers={
                    'Authorization': f'Bearer {access_token}',
                    'Content-Type': 'application/json'
                },
                json={
                    "jsonrpc": "2.0",
                    "id": 1,
                    "method": "tools/call",
                    "params": {
                        "name": products_tool,
                        "arguments": {}
                    }
                },
                timeout=30
            )
            products_response.raise_for_status()
            products_data = products_response.json()
            if 'error' in products_data:
                print(f"❌ Products list error: {products_data['error']}")
            else:
                print("✅ Products list successful")
                    
        except Exception as e:
            print(f"❌ Products list failed: {e}")
    
    print("\n🎉 Gateway testing completed!")
    print(f"\nYour gateway is ready for integration with QuickSuite!")
    print(f"Use the configuration in {config_file} for setup.")
    
    return True

def main():
    if len(sys.argv) != 2:
        print("Usage: python test_deployed_gateway.py <config_file>")
        print("Example: python test_deployed_gateway.py retail_gateway_config_abc123.json")
        sys.exit(1)
    
    config_file = sys.argv[1]
    
    if not os.path.exists(config_file):
        print(f"❌ Configuration file not found: {config_file}")
        sys.exit(1)
    
    success = test_gateway_with_curl(config_file)
    sys.exit(0 if success else 1)

if __name__ == "__main__":
    main()