default_agent: agent_latency_test
agents:
  agent_latency_test:
    name: agent_latency_test
    entrypoint: /Users/sequdian/Documents/Repos/sample-genai-startups/kiro-agents/cold-start-test/agent/agent.py
    platform: linux/arm64
    container_runtime: none
    source_path: /Users/sequdian/Documents/Repos/sample-genai-startups/kiro-agents/cold-start-test/agent
    aws:
      execution_role: arn:aws:iam::982567305797:role/AmazonBedrockAgentCoreSDKRuntime-us-west-2-2c6d875c81
      execution_role_auto_create: false
      account: '982567305797'
      region: us-west-2
      ecr_repository: 982567305797.dkr.ecr.us-west-2.amazonaws.com/bedrock-agentcore-agent_latency_test
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: agent_latency_test-sfcSmq8MqA
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:982567305797:runtime/agent_latency_test-sfcSmq8MqA
      agent_session_id: 468cb777-7c94-41cf-8c8d-e25472102451
    codebuild:
      project_name: bedrock-agentcore-agent_latency_test-builder
      execution_role: arn:aws:iam::982567305797:role/AmazonBedrockAgentCoreSDKCodeBuild-us-west-2-2c6d875c81
      source_bucket: bedrock-agentcore-codebuild-sources-982567305797-us-west-2
    memory:
      mode: STM_ONLY
      memory_id: agent_latency_test_mem-e0ZntKBDO2
      memory_arn: arn:aws:bedrock-agentcore:us-west-2:982567305797:memory/agent_latency_test_mem-e0ZntKBDO2
      memory_name: agent_latency_test_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: true
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
